package calculadora;

import static calculadora.Metodos.*;
import java.util.*;

public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EtExp = new javax.swing.JLabel();
        EtPost = new javax.swing.JLabel();
        EtRes = new javax.swing.JLabel();
        TePost = new javax.swing.JTextField();
        BoBorrar = new javax.swing.JButton();
        TeExp = new javax.swing.JTextField();
        TeRes = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BoIzq = new javax.swing.JButton();
        BoDer = new javax.swing.JButton();
        Bo7 = new javax.swing.JButton();
        Bo4 = new javax.swing.JButton();
        Bo1 = new javax.swing.JButton();
        Bo0 = new javax.swing.JButton();
        Bo2 = new javax.swing.JButton();
        BoPunto = new javax.swing.JButton();
        Bo3 = new javax.swing.JButton();
        Bo6 = new javax.swing.JButton();
        Bo5 = new javax.swing.JButton();
        Bo8 = new javax.swing.JButton();
        Bo9 = new javax.swing.JButton();
        BoPotencia = new javax.swing.JButton();
        BoResto = new javax.swing.JButton();
        BoMultiplicacion = new javax.swing.JButton();
        BoCociente = new javax.swing.JButton();
        BoResta = new javax.swing.JButton();
        BoIgual = new javax.swing.JButton();
        BoSuma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        EtError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(415, 355));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EtExp.setText("Expresión");

        EtPost.setText("Postfija");

        EtRes.setText("Resultado");

        TePost.setEditable(false);
        TePost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BoBorrar.setText("Borrar");
        BoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoBorrarActionPerformed(evt);
            }
        });

        TeExp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        TeRes.setEditable(false);
        TeRes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtExp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TePost, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TeExp)
                    .addComponent(TeRes))
                .addGap(18, 18, 18)
                .addComponent(BoBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BoBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EtExp, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(TeExp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TePost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EtRes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(TeRes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BoIzq.setText("(");
        BoIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoIzqActionPerformed(evt);
            }
        });

        BoDer.setText(")");
        BoDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoDerActionPerformed(evt);
            }
        });

        Bo7.setText("7");
        Bo7.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo7ActionPerformed(evt);
            }
        });

        Bo4.setText("4");
        Bo4.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo4ActionPerformed(evt);
            }
        });

        Bo1.setText("1");
        Bo1.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo1ActionPerformed(evt);
            }
        });

        Bo0.setText("0");
        Bo0.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo0ActionPerformed(evt);
            }
        });

        Bo2.setText("2");
        Bo2.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo2ActionPerformed(evt);
            }
        });

        BoPunto.setText(".");
        BoPunto.setPreferredSize(new java.awt.Dimension(39, 30));
        BoPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoPuntoActionPerformed(evt);
            }
        });

        Bo3.setText("3");
        Bo3.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo3ActionPerformed(evt);
            }
        });

        Bo6.setText("6");
        Bo6.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo6ActionPerformed(evt);
            }
        });

        Bo5.setText("5");
        Bo5.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo5ActionPerformed(evt);
            }
        });

        Bo8.setText("8");
        Bo8.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo8ActionPerformed(evt);
            }
        });

        Bo9.setText("9");
        Bo9.setPreferredSize(new java.awt.Dimension(39, 30));
        Bo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bo9ActionPerformed(evt);
            }
        });

        BoPotencia.setText("^");
        BoPotencia.setPreferredSize(new java.awt.Dimension(43, 30));
        BoPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoPotenciaActionPerformed(evt);
            }
        });

        BoResto.setText("%");
        BoResto.setPreferredSize(new java.awt.Dimension(43, 30));
        BoResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoRestoActionPerformed(evt);
            }
        });

        BoMultiplicacion.setText("*");
        BoMultiplicacion.setPreferredSize(new java.awt.Dimension(43, 30));
        BoMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoMultiplicacionActionPerformed(evt);
            }
        });

        BoCociente.setText("/");
        BoCociente.setPreferredSize(new java.awt.Dimension(43, 30));
        BoCociente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoCocienteActionPerformed(evt);
            }
        });

        BoResta.setText("-");
        BoResta.setPreferredSize(new java.awt.Dimension(43, 30));
        BoResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoRestaActionPerformed(evt);
            }
        });

        BoIgual.setText("=");
        BoIgual.setPreferredSize(new java.awt.Dimension(43, 23));
        BoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoIgualActionPerformed(evt);
            }
        });

        BoSuma.setText("+");
        BoSuma.setPreferredSize(new java.awt.Dimension(43, 30));
        BoSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoSumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(BoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BoResto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BoPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Bo0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BoCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BoIzq)
                    .addComponent(BoDer))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Bo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BoPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BoCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoResto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BoIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bo0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BoIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BoResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BoDer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EtError, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoBorrarActionPerformed
        TeExp.setText("");
        TePost.setText("");
        TeRes.setText("");
        EtError.setText("");
    }//GEN-LAST:event_BoBorrarActionPerformed

    private void Bo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo2ActionPerformed
        TeExp.setText(TeExp.getText()+"2");
    }//GEN-LAST:event_Bo2ActionPerformed

    private void BoIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoIzqActionPerformed
        TeExp.setText(TeExp.getText()+" ( ");
    }//GEN-LAST:event_BoIzqActionPerformed

    private void BoDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoDerActionPerformed
        TeExp.setText(TeExp.getText()+" ) ");
    }//GEN-LAST:event_BoDerActionPerformed

    private void Bo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo9ActionPerformed
        TeExp.setText(TeExp.getText()+"9");
    }//GEN-LAST:event_Bo9ActionPerformed

    private void Bo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo8ActionPerformed
        TeExp.setText(TeExp.getText()+"8");
    }//GEN-LAST:event_Bo8ActionPerformed

    private void Bo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo7ActionPerformed
        TeExp.setText(TeExp.getText()+"7");
    }//GEN-LAST:event_Bo7ActionPerformed

    private void Bo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo6ActionPerformed
        TeExp.setText(TeExp.getText()+"6");
    }//GEN-LAST:event_Bo6ActionPerformed

    private void Bo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo5ActionPerformed
        TeExp.setText(TeExp.getText()+"5");
    }//GEN-LAST:event_Bo5ActionPerformed

    private void Bo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo4ActionPerformed
        TeExp.setText(TeExp.getText()+"4");
    }//GEN-LAST:event_Bo4ActionPerformed

    private void Bo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo3ActionPerformed
        TeExp.setText(TeExp.getText()+"3");
    }//GEN-LAST:event_Bo3ActionPerformed

    private void Bo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo1ActionPerformed
        TeExp.setText(TeExp.getText()+"1");
    }//GEN-LAST:event_Bo1ActionPerformed

    private void Bo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bo0ActionPerformed
        TeExp.setText(TeExp.getText()+"0");
    }//GEN-LAST:event_Bo0ActionPerformed

    private void BoPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoPuntoActionPerformed
        TeExp.setText(TeExp.getText()+".");
    }//GEN-LAST:event_BoPuntoActionPerformed

    private void BoPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoPotenciaActionPerformed
        TeExp.setText(TeExp.getText()+" ^ ");
    }//GEN-LAST:event_BoPotenciaActionPerformed

    private void BoCocienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoCocienteActionPerformed
        TeExp.setText(TeExp.getText()+" / ");
    }//GEN-LAST:event_BoCocienteActionPerformed

    private void BoRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoRestoActionPerformed
        TeExp.setText(TeExp.getText()+" % ");
    }//GEN-LAST:event_BoRestoActionPerformed

    private void BoMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoMultiplicacionActionPerformed
        TeExp.setText(TeExp.getText()+" * ");
    }//GEN-LAST:event_BoMultiplicacionActionPerformed

    private void BoRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoRestaActionPerformed
        TeExp.setText(TeExp.getText()+" - ");
    }//GEN-LAST:event_BoRestaActionPerformed

    private void BoSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoSumaActionPerformed
        TeExp.setText(TeExp.getText()+" + ");
    }//GEN-LAST:event_BoSumaActionPerformed

    private void BoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoIgualActionPerformed
        TePost.setText("");
        TeRes.setText("");
        EtError.setText("");
        try {
            //fase1
            Stack<String> pila = new Stack<String>();
            LinkedList<String> cola = new LinkedList<String>();
            pila.push("(");
            Scanner miEscaner = new Scanner(TeExp.getText() + " )");
            while (!pila.empty()) {
                if (miEscaner.hasNext()) {
                    String aux = miEscaner.next();
                    if (esNumero(aux)) {
                        cola.add(aux);
                    }
                    else if (aux.equals("(")) {
                        pila.push(aux);
                    }
                    else if (esOperador(aux)) {
                        while (esOperador(pila.peek()) && 
                                            masPrecedente(pila.peek(), aux)) {
                            cola.add(pila.pop());
                        }
                        pila.push(aux);
                    }
                    else if (aux.equals(")")) {
                        while (!pila.peek().equals("(")) {
                            cola.add(pila.pop());
                        }
                        pila.pop();
                    } else {
                        throw new Exception();
                    }
                } else {
                    throw new Exception();
                }
            }
            //fase2
            Stack<Double> pila2 = new Stack<Double>();
            while(!cola.isEmpty()){
                TePost.setText(TePost.getText()+cola.element()+" ");
                if (esNumero(cola.element())) {
                    pila2.push(Double.parseDouble(cola.remove()));
                    TeRes.setText(TeRes.getText()+pila2.peek()+" ");
                } else {
                    double y = pila2.pop();
                    double x = pila2.pop();
                    pila2.push(operar(cola.remove(), x, y));
                    TeRes.setText(TeRes.getText()+pila2.peek()+" ");
                }
            }
            TeRes.setText(pila2.peek().toString());
        } catch (Exception e) {
            EtError.setText("Expresión mal formada");
            TePost.setText("");
            TeRes.setText("");
        }
        
 
    }//GEN-LAST:event_BoIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bo0;
    private javax.swing.JButton Bo1;
    private javax.swing.JButton Bo2;
    private javax.swing.JButton Bo3;
    private javax.swing.JButton Bo4;
    private javax.swing.JButton Bo5;
    private javax.swing.JButton Bo6;
    private javax.swing.JButton Bo7;
    private javax.swing.JButton Bo8;
    private javax.swing.JButton Bo9;
    private javax.swing.JButton BoBorrar;
    private javax.swing.JButton BoCociente;
    private javax.swing.JButton BoDer;
    private javax.swing.JButton BoIgual;
    private javax.swing.JButton BoIzq;
    private javax.swing.JButton BoMultiplicacion;
    private javax.swing.JButton BoPotencia;
    private javax.swing.JButton BoPunto;
    private javax.swing.JButton BoResta;
    private javax.swing.JButton BoResto;
    private javax.swing.JButton BoSuma;
    private javax.swing.JLabel EtError;
    private javax.swing.JLabel EtExp;
    private javax.swing.JLabel EtPost;
    private javax.swing.JLabel EtRes;
    private javax.swing.JTextField TeExp;
    private javax.swing.JTextField TePost;
    private javax.swing.JTextField TeRes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}

